name = "AEGIS-M"
prefix = "aegism"
mainprefix = "x"

[properties]
author = "Snow(Dryden)"

[version]
major = 0
minor = 1
patch = 0
build = 0
git_hash = 0

[files]
include = [
    "mod.cpp",
    "LICENSE",
    "README.md",
]

[hemtt.release]
sign = true
archive = true
