name = "AEGIS-M"
prefix = "aegism"
mainprefix = "x"

[properties]
author = "Snow(Dryden)"

[version]
major = 1
minor = 0
patch = 0
build = 0
git_hash = 0

[files]
include = [
    "mod.cpp",
    "LICENSE",
    "README.md",
    "logo.paa",
    "logo_over.paa",
    "logo_small.paa",
    "picture.paa",
]

[hemtt.release]
sign = true
archive = true
